version: '3.9'

services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: salesapi_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: f2{GVsq85]ca$
      POSTGRES_DB: sales_api
    ports:
      - "5433:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: salesapi_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"    
      - "15672:15672"   
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
